# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date_released', models.CharField(blank=True, max_length=255)),
                ('date_update', models.CharField(blank=True, max_length=255)),
                ('tools', models.CharField(blank=True, max_length=255)),
                ('serving_dish', models.CharField(blank=True, max_length=255)),
                ('cooking_time', models.CharField(blank=True, max_length=255)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('ingridients_headers', models.CharField(blank=True, max_length=5000)),
                ('ingridients', models.CharField(blank=True, max_length=5000)),
                ('dish_output', models.CharField(blank=True, max_length=5000)),
                ('cooking_technology', models.CharField(blank=True, max_length=255)),
                ('nutrition_caloricity', models.CharField(blank=True, max_length=255)),
                ('nutrition_proteins', models.CharField(blank=True, max_length=255)),
                ('nutrition_fats', models.CharField(blank=True, max_length=255)),
                ('nutrition_carbohydrates', models.CharField(blank=True, max_length=255)),
                ('decor_delivery', models.CharField(blank=True, max_length=255)),
                ('organoleptic_stats', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
