# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_technology',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='organoleptic_stats',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
